routes/web.php
<?php

use App\Http\Controllers\Mail\BuyNotification;
use Carbon\Carbon;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Web\HomeController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\HomeController as AdminHomeController;
use App\Http\Controllers\Admin\EventsController;
use \App\Http\Controllers\Admin\CategoriesController;
use App\Http\Controllers\Admin\PlacesController;
use App\Http\Controllers\Admin\CheckController;
use App\Http\Controllers\Web\EventController as WebEventController;
use App\Http\Controllers\Web\UserController as WebUserController;
use App\Http\Controllers\Web\OrganizerController;
use App\Http\Controllers\Web\OrdersController;
use App\Http\Controllers\Web\PaymentController;
use App\Http\Controllers\Web\CouponsController;
use App\Http\Controllers\Web\PlacesController as WebPlacesController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * Typeahead Search
 */
/*Route::get('testpay', function (){
    $order = \App\Orders::orderBy('created_at', 'desc')->first();

    //dd($order->detail);
    return view('web.mailing.mailing-paymet', compact('order'));
});*/

Route::get('/test/mail/',function () {

    //dd(QrCode::generate("Chupame esta",public_path('test_qr')));


    $order = \App\Orders::with('tickets','detail.sector')->find(108);

    Mail::to('rarrua2009@gmail.com')->send(new BuyNotification($order));
    echo "se envio el mail";

});

Route::get('check/tikect/hash/{hash}',[HomeController::class,'checkTicketHast'])->name('check.ticket.hash');

Route::get('find', [SearchController::class,'find']);

//Route::get('search', 'Admin\UsersController@usersSearch')->name('search');

Route::get('search', [SearchController::class,'searchAll'])->name('web.search');


Route::get('/login/{provider}', [LoginController::class,'redirectToProvider'])
    ->name('social.login');
Route::get('/login/{provider}/callback', [LoginController::class,'handleProviderCallback'])
    ->name('social.callback');



/**
 * Admin
 */
/*Route::livewire('/catsave', 'admin.categories.create')->name('save');*/
Route::group(['middleware' => ['auth', 'role:admin'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/auxpwd/{email}/{pwd}', [UsersController::class,'auxUpdatePwd'])->name('auxpwd');

    Route::get('/', [AdminHomeController::class,'index'])->name('home');
    Route::get('/users/create', [UsersController::class,'create'])->name('users.create');

    Route::resource('users', UsersController::class);
    Route::resource('events', EventsController::class);
    Route::resource('categories', CategoriesController::class);


    /**
     * Event Menu
     */
    Route::post('/event/show', [EventsController::class,'showEvent'])->name('event.show');
    Route::get('/event/dashboard', [EventsController::class,'eventDashboard'])->name('event.dashboard');
    Route::get('/event/info', [EventsController::class,'eventInformation'])->name('event.info');
    Route::get('/event/payments', [EventsController::class,'eventPayments'])->name('event.payments');
    Route::get('/event/payments/details/{order_id}', [EventsController::class,'eventPaymentsDetails'])->name('event.payments.details');
    Route::get('/event/orders/payments/{order_id}', [EventsController::class,'eventPaymentsOrders'])->name('event.orders.paynments');
    Route::post('/event/info/store', [EventsController::class,'eventInfoStore'])->name('event.info.store');

    /* Sectors */
    Route::get('/event/sectors/{id?}', [EventsController::class,'eventSectors'])->name('event.sectors');
    //Route::post('/event/sectors/', 'Admin\EventsController@sectorStore')->name('event.sectors.store');
    Route::post('/event/sectors/store', [EventsController::class,'sectorStore'])->name('event.sectors.store');
    //Route::post('/event/sectors/update', 'Admin\EventsController@sectorStore')->name('event.sectors.store');
    Route::delete('/event/sector/delete/{sector}', [EventsController::class,'sectorDelete'])->name('event.sectors.delete');

    /* Dates */
    Route::get('/event/dates/{id?}', [EventsController::class,'eventDates'])->name('event.dates');
    Route::post('/event/dates/store', [EventsController::class,'dateStore'])->name('event.dates.store');
    Route::delete('/event/dates/delete/{date}', [EventsController::class,'dateDelete'])->name('event.dates.delete');

    /* Promotions */
    Route::get('/event/promotions/{id?}', [EventsController::class,'eventPromotions'])->name('event.promotions');
    Route::post('/event/promotions/store', [EventsController::class,'promotionsStore'])->name('event.promotions.store');
    Route::get('/event/promotions/delete/{event}/{date}', [EventsController::class,'promotionsDelete'])->name('event.promotions.delete');


    /**
     * Scan ticket
     */
    Route::get('/scan/', [CheckController::class,'scan'])->name('scan');

});

Route::group(['middleware' => ['auth', 'role:admin|place'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    /* Places */
    Route::get('/places', [PlacesController::class,'index'])->name('places.index');
    Route::get('/places/create', [PlacesController::class,'create'])->name('places.create');
    Route::post('/places/store', [PlacesController::class,'store'])->name('places.store');
    Route::get('/places/{id}/edit', [PlacesController::class,'edit'])->name('places.edit');
    Route::post('/places/file/store', [PlacesController::class,'storeFile'])->name('places.file.store');
    Route::post('/places/file/sort', [PlacesController::class,'sortFiles'])->name('places.file.sort');
    Route::get('/places/file/delete/{file}/{place}', [PlacesController::class,'deleteFile'])->name('places.file.delete');
    Route::put('/places/update/{date}', [PlacesController::class,'update'])->name('places.update');

    Route::get('/places/{id}/clients', [PlacesController::class,'clients'])->name('places.clients');
    Route::get('/places/{id}/registers', [PlacesController::class,'registers'])->name('places.registers');
    Route::get('/places/{id}/reservations', [PlacesController::class,'reservations'])->name('places.reservations');
    Route::get('/places/{id}/suggestions', [PlacesController::class,'suggestions'])->name('places.suggestions');
});

Route::get('/', [HomeController::class,'index'])->name('home');

Auth::routes(['verify' => true]);

Route::group(['middleware' => ['auth']], function () {
    /**
     * Events
     */
    Route::get('/event/step1', [WebEventController::class,'step1'])->name('web.event.step1');
    Route::match(['get', 'post'], '/event/step2', [WebEventController::class,'step2'])->name('web.event.step2');
    Route::match(['get', 'post'], '/event/step3', [WebEventController::class,'step3'])->name('web.event.step3');
    Route::match(['get', 'post'], '/event/step4', [WebEventController::class,'step4'])->name('web.event.step4');
    Route::post('/event/save', [WebEventController::class,'event_save'])->name('web.event.save');
    Route::get('/event/finish/{slug}', [WebEventController::class,'eventFinish'])->name('web.event.finish');

    /**
     * Client
     */
    Route::get('/user/profile', [WebUserController::class,'profile'])->name('web.user.profile');
    Route::get('/user/history', [WebUserController::class,'history'])->name('web.user.history');
    Route::get('/user/history-detail/{id}', [WebUserController::class,'historyDetail'])->name('web.user.history.detail');
    Route::post('/user/profile-update/{id}', [WebUserController::class,'profileUpdate'])->name('web.user.profile_update');
    Route::get('/user/payments', [WebUserController::class,'payments'])->name('web.user.payments');
    Route::get('/user/purchased_events', [WebUserController::class,'purchased_events'])->name('web.user.purchased_events');

    /*
     * Organizer
     */
    Route::get('/organizer', [OrganizerController::class,'index'])->name('web.organizer.index');
    Route::get('/organizer/event/{id}/edit', [OrganizerController::class,'eventEdit'])->name('web.organizer.event.edit');
    Route::get('/organizer/event/{id}/show', [OrganizerController::class,'eventShow'])->name('web.organizer.event.show');
    Route::get('/organizer/event/{id}/control/tickets', [OrganizerController::class,'controlTickets'])->name('web.organizer.control.tickets');
    Route::get('/organizer/event/{id}/sale/tickets', [OrganizerController::class,'saleTickets'])->name('web.organizer.sale.tickets');
    Route::get('/organizer/event/{id}/{order_details_id}/tickets/status', [OrganizerController::class,'eventShowTicketsStatus'])
        ->name('web.organizer.event.ticket.status');

    Route::get('/organizer/promotions/create', [OrganizerController::class,'promotionCreate'])->name('web.organizer.promotions.create');

    /**
     * Checkout
     */
    Route::get('/orders/checkout', [OrganizerController::class,'checkout'])->name('web.orders.checkout');
    Route::get('/orders/checkout/payment', [OrganizerController::class,'checkoutPayment'])->name('web.orders.checkout.payment');
    //Route::match(['get', 'post'], '/orders/checkout/finish/{hash?}', 'Web\OrdersController@checkoutFinish')->name('web.orders.checkout.finish');

    Route::post('/coupons', [CouponsController::class,'store'])->name('web.coupons.store');

});

Route::group(['middleware' => ['web','auth']], function () {
    Route::match(['get', 'post'], '/orders/checkout/finish/{hash?}', [OrdersController::class,'checkoutFinish'])->name('web.orders.checkout.finish');
});

/*
 * Pagopar
 */

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Categories;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //dump('AA');
        $categories = Categories::all();
        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $category = Categories::create($request->except('_token'));

        return redirect()->back()->with('success', 'Se ha creado la categoría '.$category->category_name.' exitósamente.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Categories::find($id);

        return view('admin.categories.form', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Categories::find($id);
        $category->update($request->except('_token'));

        return redirect()->back()->with('success', 'Se actualizado la categoría '.$category->category_name.' correctamente.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/categories/form.blade.php
@extends('admin.templates.layout')
@section('content')
    <div class="row">
        <div class="col-12 col-md-12 col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h4>Categorias</h4>
                </div>
                @isset($category)
                    {!! Form::model($category, ['route' => ['admin.categories.update', $category->id], 'method' => 'put']) !!}
                @else
                    {!! Form::open(['route' => 'admin.categories.store', 'method' => 'post']) !!}
                @endisset
                {{--{!! Form::open(['route' => 'admin.categories.store', 'method' => 'post']) !!}--}}
                <div class="card-body">

                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="nombres">Categoría</label>

                            {!! Form::text('category_name', old('category_name'), ['class' => 'form-control']) !!}
                            {{--<input type="text" class="form-control @error('category_name') is-invalid @enderror"
                                   id="nombres"
                                   name="category_name" placeholder="Categoría" value="{{ old('category_name') }}">
                            @error('category_name')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror--}}
                        </div>
                    </div>
                </div>

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script>
        function submit() {
            console.log($('#usuariosForm'))
        }
    </script>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.templates.layout')
@section('content')
    <div class="row">
        <div class="col-12 col-md-12 col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h4>Categorías</h4>
                    <div class="card-header-form">
                        <form>
                            <div class="input-group">
                                <div class="input-group-btn">
                                    <a href="{{ route('admin.categories.create') }}" class="btn btn-primary"><i class="fas fa-plus"> Crear</i>
                                    </a>
                                </div>
                                &nbsp;
                                <input type="text" class="form-control" placeholder="Search">
                                <div class="input-group-btn">
                                    <button class="btn btn-primary"><i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="card-body p-0">
                    <div class="table-responsive">
                        {{--<input type="checkbox" name="custom-switch-checkbox" class="custom-switch-input">
                        <span class="custom-switch-indicator"></span>--}}
                        <table class="table table-striped">
                            <tr>
                                <th class="text-center">
                                    #
                                </th>
                                <th>Categoría</th>
                                <th>Estado</th>
                                <th>Creado</th>
                                <th>Actualizado</th>
                                <th>Acciones</th>
                            </tr>

                            @foreach($categories as $category)
                                <tr>
                                    <td class="p-0 text-center">{{ $category->id }}</td>
                                    <td>{{ $category->category_name }}</td>
                                    <td></td>
                                    {{--<td><div class="badge badge-success">Completed</div></td>--}}
                                    <td>{{ $category->created_at }}</td>
                                    <td>{{ $category->updated_at }}</td>
                                    <td><a href="{{ route('admin.categories.edit', [$category->id]) }}" class="btn btn-primary">Detail</a></td>
                                </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script src="/assets/js/page/forms-advanced-forms.js"></script>

    <script>
        function submit() {
            console.log($('#usuariosForm'))
        }
    </script>
@endsection